"""Initial migration

Revision ID: 2cf76bff659a
Revises: 
Create Date: 2024-09-19 12:33:21.062222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '2cf76bff659a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulation_segments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('regulation_id', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.Vector(
                        dim=768), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('sop_on_regulations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('regulation_id', sa.Integer(), nullable=False),
                    sa.Column('similarity', sa.REAL(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.Vector(
                        dim=768), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    
    op.create_table('sop_segment_on_regulation_segment',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('sop_segment_id', sa.Integer(), nullable=False),
                sa.Column('regulation_segment_id', sa.Integer(), nullable=False),
                sa.Column('similarity', sa.Integer(), nullable=False),
                sa.Column('embedding', pgvector.sqlalchemy.Vector(
                    dim=768), nullable=True),
                sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_regulation_segments_id'),
                    'regulation_segments', ['id'], unique=False)
    op.create_index(op.f('ix_regulation_segments_regulation_id'),
                    'regulation_segments', ['regulation_id'], unique=False)
    op.create_table('regulations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_regulations_id'),
                    'regulations', ['id'], unique=False)
    op.create_index(op.f('ix_regulations_name'),
                    'regulations', ['name'], unique=False)
    op.create_table('sop_segments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sop_id', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.Vector(
                        dim=768), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_sop_segments_id'),
                    'sop_segments', ['id'], unique=False)
    op.create_index(op.f('ix_sop_segments_sop_id'),
                    'sop_segments', ['sop_id'], unique=False)
    op.create_table('sops',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('url', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_sops_id'), 'sops', ['id'], unique=False)
    op.create_index(op.f('ix_sops_name'), 'sops', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sops_name'), table_name='sops')
    op.drop_index(op.f('ix_sops_id'), table_name='sops')
    op.drop_table('sops')
    op.drop_index(op.f('ix_sop_segments_sop_id'), table_name='sop_segments')
    op.drop_index(op.f('ix_sop_segments_id'), table_name='sop_segments')
    op.drop_table('sop_segments')
    op.drop_index(op.f('ix_regulations_name'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_id'), table_name='regulations')
    op.drop_table('regulations')
    op.drop_index(op.f('ix_regulation_segments_regulation_id'),
                  table_name='regulation_segments')
    op.drop_index(op.f('ix_regulation_segments_id'),
                  table_name='regulation_segments')
    op.drop_table('regulation_segments')
    # ### end Alembic commands ###
