"""add name to reg segment

Revision ID: 373226769aa4
Revises: cedffa5a0816
Create Date: 2024-10-01 16:05:27.250705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373226769aa4'
down_revision: Union[str, None] = 'cedffa5a0816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_segments', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_segments', 'name')
    # ### end Alembic commands ###
