"""add name to reg segment

Revision ID: 39be0fa55dff
Revises: 52176e08234d
Create Date: 2024-10-01 19:16:18.396606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39be0fa55dff'
down_revision: Union[str, None] = '52176e08234d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_segments', sa.Column('has_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_segments', 'has_changed')
    # ### end Alembic commands ###
