"""add content

Revision ID: 3ba426766055
Revises: 2cf76bff659a
Create Date: 2024-09-23 12:12:45.571554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba426766055'
down_revision: Union[str, None] = '2cf76bff659a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_segments', sa.Column('raw_content', sa.String(), nullable=True))
    op.drop_index('ix_regulation_segments_regulation_id', table_name='regulation_segments')
    op.create_foreign_key(None, 'regulation_segments', 'regulations', ['regulation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('sop_segments', sa.Column('raw_content', sa.String(), nullable=True))
    op.drop_index('ix_sop_segments_sop_id', table_name='sop_segments')
    op.create_foreign_key(None, 'sop_segments', 'sops', ['sop_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sop_segments', type_='foreignkey')
    op.create_index('ix_sop_segments_sop_id', 'sop_segments', ['sop_id'], unique=False)
    op.drop_column('sop_segments', 'raw_content')
    op.drop_constraint(None, 'regulation_segments', type_='foreignkey')
    op.create_index('ix_regulation_segments_regulation_id', 'regulation_segments', ['regulation_id'], unique=False)
    op.drop_column('regulation_segments', 'raw_content')
    # ### end Alembic commands ###
