"""add name to reg segment

Revision ID: 3d7ffbcec3be
Revises: 373226769aa4
Create Date: 2024-10-01 18:50:34.560782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7ffbcec3be'
down_revision: Union[str, None] = '373226769aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sops', sa.Column('has_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sops', 'has_changed')
    # ### end Alembic commands ###
