"""add content

Revision ID: 82e3b007c969
Revises: eec2986f476e
Create Date: 2024-09-24 14:30:52.658361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e3b007c969'
down_revision: Union[str, None] = '3ba426766055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulations', sa.Column('latest_amendment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulations', 'latest_amendment_date')
    # ### end Alembic commands ###
