"""add name to reg segment

Revision ID: c4566a03c1a0
Revises: 39be0fa55dff
Create Date: 2024-10-03 13:01:41.433713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4566a03c1a0'
down_revision: Union[str, None] = '39be0fa55dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('sop_segment_on_regulation_segment', 'similarity',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=True)
  
    op.create_foreign_key(None, 'sop_segment_on_regulation_segment', 'sop_segments', [
                          'sop_segment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sop_segment_on_regulation_segment', 'regulation_segments', [
                          'regulation_segment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sop_segment_on_regulation_segment', sa.Column(
        'regulation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sop_segment_on_regulation_segment', sa.Column(
        'sop_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(
        None, 'sop_segment_on_regulation_segment', type_='foreignkey')
    op.drop_constraint(
        None, 'sop_segment_on_regulation_segment', type_='foreignkey')
    op.create_foreign_key('sop_segment_on_regulation_segment_sop_id_fkey', 'sop_segment_on_regulation_segment', 'sops', [
                          'sop_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('sop_segment_on_regulation_segment_regulation_id_fkey', 'sop_segment_on_regulation_segment', 'regulations', [
                          'regulation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('sop_segment_on_regulation_segment', 'similarity',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=True)
    op.drop_column('sop_segment_on_regulation_segment',
                   'regulation_segment_id')
    op.drop_column('sop_segment_on_regulation_segment', 'sop_segment_id')
    # ### end Alembic commands ###
