"""add abstract and owner

Revision ID: cedffa5a0816
Revises: 3bbdb93463c3
Create Date: 2024-10-01 15:44:20.507680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedffa5a0816'
down_revision: Union[str, None] = '3bbdb93463c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulations', sa.Column('abstract', sa.String(), nullable=True))
    op.add_column('sops', sa.Column('abstract', sa.String(), nullable=True))
    op.add_column('sops', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sops', 'owner')
    op.drop_column('sops', 'abstract')
    op.drop_column('regulations', 'abstract')
    # ### end Alembic commands ###
