"""add content

Revision ID: f6ab9e6b0ab3
Revises: 71cf339831e7
Create Date: 2024-09-24 15:08:09.069919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ab9e6b0ab3'
down_revision: Union[str, None] = '82e3b007c969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulations', sa.Column('title', sa.String(), nullable=True))
    op.add_column('regulations', sa.Column('part', sa.String(), nullable=True))
    op.create_index(op.f('ix_regulations_part'), 'regulations', ['part'], unique=False)
    op.create_index(op.f('ix_regulations_title'), 'regulations', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulations_title'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_part'), table_name='regulations')
    op.drop_column('regulations', 'part')
    op.drop_column('regulations', 'title')
    # ### end Alembic commands ###
