"""add name to reg segment

Revision ID: fce61c6bb741
Revises: 1df9d84ea444
Create Date: 2024-10-03 14:07:59.705552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce61c6bb741'
down_revision: Union[str, None] = '1df9d84ea444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sop_segment_on_regulation_segment', 'similarity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('sop_segments', sa.Column('has_changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sop_segments', 'has_changed')
    op.alter_column('sop_segment_on_regulation_segment', 'similarity',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
